os:
  - linux
  - osx
osx_image: xcode8.3
dist: trusty
sudo: false

# For testing only:
#branches:
#  only:
#    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

# Do not use Travis Python to save some time.
language: generic
env:
  matrix:
  - MYCONDAPY=2.7
  - MYCONDAPY=3.5
  - MYCONDAPY=3.6
  global:
    # ANACONDA_TOKEN encrypted
    secure: "P5oCCSZgfntpxwYm0pe7J0EWebQ3iF7p7+XGeE5FJoOqfQAZBZXujcaHMcej0UtyLq/IkfHabX+DURuqc8OWKQBCgy224UD+qdYnlZclfrz5M8DMp/iplbkzJsXj3zjug/br5R2YBN5tVyFQPBbJAKQ0A52rZj+avOhOt1qKEpM="
    - PYPKG=molmod
    - GITHUB_REPO=molmod
    - GITHUB_ORG=molmod
install:
# Get miniconda. Take the right version, so re-installing python is only needed for 3.5.
- if [[ "$MYCONDAPY" == "2.7" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  else
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Get the right python version for building. This only does something for 3.5.
# Install extra package needed to make things work. Most things can be listed as
# dependencies on metal.yaml and setup.py, unless setup.py already imports them.
# Install conda tools for packaging and uploading
- conda install python=${MYCONDAPY} numpy cython sphinx conda-build anaconda-client
- conda info -a

script:
# Check if code is normalized properly, whitespace etc
- wget https://raw.githubusercontent.com/tovrstra/devscripts/master/scripts/ds-normalize-code -O ds-normalize-code;
  chmod +x ds-normalize-code;
  ./ds-normalize-code;

# Build the conda package
- conda build -q tools/conda.recipe

# Build source package, should work too and needed for deployment to Github and
# PyPI.
- python setup.py sdist

# Install Conda package
- conda install --use-local $PYPKG

# Compile documentation
- (cd doc; make html)

# Run tests out of source tree, to make sure that installed version is tested.
- (cd; nosetests $PYPKG -v --processes=2 --detailed-errors --process-timeout=600)

# In deployment, the env var TRAVIS_TAG contains the name of the current tag, if any.
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    # Encrypted github token
    secure: cfs7wOx9Q4LXFIvZvxSDVtCT1dNpuMQHMODK50CS4mstR0ppZab62YpJLLEQVfhLsaqNVdBM3fCWm03LndbUcdB9dHkKnELh+Gj6Y/E9zA/1QkQau4yTjVG2Pb16If4doHwMrny08m1daOcpDFNfpXFszNieidOs6dsLw/ZbbEQ=
  file: dist/${PYPKG}-${TRAVIS_TAG}.tar.gz
  on:
    repo: ${GITHUB_ORG}/${GITHUB_REPO}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
  prerelease: false
- provider: releases
  skip_cleanup: true
  api_key:
    # Encrypted github token
    secure: cfs7wOx9Q4LXFIvZvxSDVtCT1dNpuMQHMODK50CS4mstR0ppZab62YpJLLEQVfhLsaqNVdBM3fCWm03LndbUcdB9dHkKnELh+Gj6Y/E9zA/1QkQau4yTjVG2Pb16If4doHwMrny08m1daOcpDFNfpXFszNieidOs6dsLw/ZbbEQ=
  file: dist/${PYPKG}-${TRAVIS_TAG}.tar.gz
  on:
    repo: ${GITHUB_ORG}/${GITHUB_REPO}
    tags: true
    condition: "$TRAVIS_TAG == *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
  prerelease: true
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l alpha ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_ORG}/${GITHUB_REPO}
    tags: true
    condition: "$TRAVIS_TAG == *a*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l beta ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_ORG}/${GITHUB_REPO}
    tags: true
    condition: "$TRAVIS_TAG == *b*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l main ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_ORG}/${GITHUB_REPO}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]*"
- provider: pypi
  skip_cleanup: true
  user: tovrstra
  password:
    # Encrypted PyPI password
    secure: "FqhLt9p9lWnI7XsAZjJfdRKwdteHSCIR/7f87QQ1ZnLRxjML33ndz++Me2P0Ceps1Z8qgRuOQstPvlhyCVk9aKVoAhwOtHSmcBz/IHsYTIo0PVmZqPSGqDqhF1zkTudTVDYRBHlR8bCNQW82hIxNhNBaRCeKbku/nBBdYxTWrG8="
  on:
    repo: ${GITHUB_ORG}/${GITHUB_REPO}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
- provider: pages
  skip_cleanup: true
  github_token:
    secure: cfs7wOx9Q4LXFIvZvxSDVtCT1dNpuMQHMODK50CS4mstR0ppZab62YpJLLEQVfhLsaqNVdBM3fCWm03LndbUcdB9dHkKnELh+Gj6Y/E9zA/1QkQau4yTjVG2Pb16If4doHwMrny08m1daOcpDFNfpXFszNieidOs6dsLw/ZbbEQ=
  project_name: ${PYPKG}
  local_dir: doc/_build/html
  on:
    repo: ${GITHUB_ORG}/${GITHUB_REPO}
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
    tags: true
