os:
  - linux
  - osx
osx_image: xcode8.3
dist: trusty
sudo: false

# For testing only:
#branches:
#  only:
#    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

# Do not use Travis Python to save some time.
language: generic
env:
  matrix:
  - MYCONDAPY=2.7
  - MYCONDAPY=3.5
  - MYCONDAPY=3.6
  global:
    # ANACONDA_TOKEN
    - secure: "aIgSD/nhnWU9ztVeRkDPBCg/zI48TtIgeTJL0tsBSKB42T9wVlxp2Muod50r1rZOZjtY/S4lFiXJhSkVOPP3nKAp+I4mCJC5ey0wthSCWv8pB4OBsjqYGpK28Th0h2lqgWwvZ5KuFb7qr0drqEVxpQezPdffwZRvpPqDLzhNqck="
    # GITHUB_TOKEN
    - secure: "NrofdkaGtI5wasllKNqBQsYWupcm3FtpVpCfoUSe753mq/SI6+THUnyWg1oakgtlwVgcXghDevieWIaCEXUGVtLANl7KHK1R60n/Byb3eOYi/HwU2TfefrC3YyqM3P8xaCam4wxtp6BRnsX/wVUbRggfkba/WqJlN2nXgVP/emU="
    # PYPI_PASSWD
    - secure: "O/IuiNJ0j3M64WlNZHis/RGdoa26LiDzzUh60yFJd7J8VIATfJSVObn342ToY/vcWmt+zYAsaouNzm729DUJ1bj80Zzuwrftb/5sgP5Z/QkwdsHfukke4vXa6zyrPQxMEDhfaO0St3zUznSjCT4vQJlTL7cCBOun+sIhOT807qM="
    - PYPKG=molmod
    - GITHUB_REPO_NAME=molmod/molmod
install:
# Get miniconda. Take the right version, so re-installing python is only needed for 3.5.
- if [[ "$MYCONDAPY" == "2.7" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  else
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r

# Configure conda and get a few essentials
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Get the right python version for building. This only does something for 3.5.
# Install extra package needed to make things work. Most things can be listed as
# dependencies on metal.yaml and setup.py, unless setup.py already imports them.
# Install conda tools for packaging and uploading
- conda install python=${MYCONDAPY} numpy cython sphinx conda-build anaconda-client
- conda info -a

script:
# Check if code is normalized properly, whitespace etc
- wget https://raw.githubusercontent.com/tovrstra/devscripts/master/scripts/ds-normalize-code -O ds-normalize-code;
  chmod +x ds-normalize-code;
  ./ds-normalize-code;

# Build the conda package
- git fetch origin --tags
- conda build -q tools/conda.recipe

# Build source package, should work too and needed for deployment to Github and
# PyPI.
- python setup.py sdist

# Install Conda package
- conda install --use-local $PYPKG

# Compile documentation
- (cd doc; make html)

# Run tests out of source tree, to make sure that installed version is tested.
- (cd; nosetests $PYPKG -v --processes=2 --detailed-errors --process-timeout=600)

# In deployment, the env var TRAVIS_TAG contains the name of the current tag, if any.
deploy:
- provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_TOKEN}
  file: dist/${PYPKG}-${TRAVIS_TAG}.tar.gz
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
  prerelease: false
- provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_TOKEN}
  file: dist/${PYPKG}-${TRAVIS_TAG}.tar.gz
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG == *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
  prerelease: true
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l alpha ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG == *a*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l beta ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG == *b*"
- provider: script
  skip_cleanup: true
  script: anaconda -t $ANACONDA_TOKEN upload -l main ${HOME}/miniconda/conda-bld/*/${PYPKG}-*.tar.bz2
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]*"
- provider: pypi
  skip_cleanup: true
  user: tovrstra
  password: ${PYPI_PASSWD}
  on:
    repo: ${GITHUB_REPO_NAME}
    tags: true
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
- provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  project_name: ${PYPKG}
  local_dir: doc/_build/html
  on:
    repo: ${GITHUB_REPO_NAME}
    condition: "$TRAVIS_TAG != *[ab]* && $MYCONDAPY == 2.7 && $TRAVIS_OS_NAME == linux"
    tags: true
