package:
  version: '{{ GIT_DESCRIBE_TAG }}'
  name: 'molmod'

source:
  path: ../

build:
  number: 0
  script: python setup.py install

requirements:
  run:
    - python
    - numpy
    - nose
  build:
    - python
    - numpy
    - gcc
    - cython
    - setuptools

about:
  dev_url: https://github.com/molmod/molmod
  description: MolMod is a collection of molecular modelling tools for python.
  license: GNU General Public License (GPL)
  license_family: GPL
  summary: MolMod is a collection of molecular modelling tools for python.
  home: https://github.com/molmod/molmod
  license_file: LICENSE.txt
  doc_url: https://github.com/molmod/molmod

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
